name: Build Native Libs

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version number (package)

permissions:
  packages: write
  contents: read

jobs:
  build-platforms:
      name: ${{ matrix.targetname }}-${{ matrix.arch }}
      runs-on: ${{ matrix.buildos }}

      env:
        VCPKG_OVERLAY_TRIPLETS: ${{ github.workspace }}/native/build/triplets
        VCPKG_TARGET_TRIPLET: ${{ matrix.triplet }}
        CMAKE_BUILD_TYPE: Release

        ARCHIVE_DIR: ${{ github.workspace }}/archive-${{ matrix.targetname }}
        BUILD_DIR: ${{ github.workspace }}/build-${{ matrix.arch }}

      strategy:
        fail-fast: false
        matrix:
          include:
            - { targetname: osx, buildos: macos-latest, arch: x64, triplet: release-osx-x64 }
            - { targetname: osx, buildos: macos-latest, arch: arm64, triplet: release-osx-arm64 }
            - { targetname: linux, buildos: ubuntu-20.04, arch: x64, triplet: release-linux-x64 }
            - { targetname: linux, buildos: ubuntu-20.04, arch: arm64, triplet: release-linux-arm64 }
            - { targetname: windows, buildos: windows-latest, arch: x64, triplet: release-windows-x64 }
            - { targetname: windows, buildos: windows-latest,  arch: arm64, triplet: release-windows-arm64 }

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
            fetch-depth: 0

        - name: Install Additional Packages (Ubuntu)
          if: matrix.buildos == 'ubuntu-20.04' && matrix.arch == 'arm64'
          run: |
            sudo apt-get update
            sudo apt-get install -y binutils-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-aarch64-linux-gnu

        - name: Setup VCPKG
          uses: lukka/run-vcpkg@v11

        - name: Setup CMake (Linux)
          if: matrix.targetname == 'linux'
          run: cmake -B ${{ env.BUILD_DIR }} -S .
          env:
            CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/native/build/linux-${{ matrix.arch }}.cmake

        - name: Setup CMake (Windows)
          if: matrix.targetname == 'windows'
          run: cmake -B ${{ env.BUILD_DIR }} -G "Visual Studio 17 2022" -A ${{ matrix.arch == 'arm64' && 'ARM64' || 'x64' }} -S .
          env:
            CMAKE_TOOLCHAIN_FILE: ${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
              
        - name: Setup CMake (macOS)
          if: matrix.targetname == 'osx'
          run: cmake -B ${{ env.BUILD_DIR }} -G "Xcode" -S .
          env:
            CMAKE_TOOLCHAIN_FILE: ${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
            CMAKE_OSX_ARCHITECTURES: ${{ matrix.arch == 'arm64' && 'arm64' || 'x86_64' }}

        - name: Build
          run: cmake --build ${{ env.BUILD_DIR }} --config Release

        - name: Prepare Directory
          run: mkdir ${{ env.ARCHIVE_DIR }}

        - name: Prepare Files (Linux)
          if: matrix.targetname == 'linux'
          run: |
            cp ${{ env.BUILD_DIR }}/libcsdl.so ${{ env.ARCHIVE_DIR }}
            cp ${{ env.BUILD_DIR }}/vcpkg_installed/${{ matrix.triplet }}/lib/libtorrent-rasterbar.so.2.0 ${{ env.ARCHIVE_DIR }}

        - name: Prepare Files (macOS)
          if: matrix.targetname == 'osx'
          run: |
            cp ${{ env.BUILD_DIR }}/Release/libcsdl.dylib ${{ env.ARCHIVE_DIR }}
            cp ${{ env.BUILD_DIR }}/vcpkg_installed/${{ matrix.triplet }}/lib/libtorrent-rasterbar.2.0.dylib ${{ env.ARCHIVE_DIR }}

        - name: Prepare Files (Windows)
          if: matrix.targetname == 'windows'
          run: |
            cp ${{ env.BUILD_DIR }}/Release/csdl.dll ${{ env.ARCHIVE_DIR }}
            cp ${{ env.BUILD_DIR }}/vcpkg_installed/${{ matrix.triplet }}/lib/libtorrent-rasterbar.dll ${{ env.ARCHIVE_DIR }}

        - name: Upload
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.targetname }}-${{ matrix.arch }}
            path: ${{ env.ARCHIVE_DIR }}/*

  package:
    name: Build Package
    runs-on: ubuntu-latest

    needs: [build-platforms]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: osx-x64
          path: native/nuget/runtimes/osx-x64/native

      - uses: actions/download-artifact@v4
        with:
          name: osx-arm64
          path: native/nuget/runtimes/osx-arm64/native

      - uses: actions/download-artifact@v4
        with:
          name: windows-x64
          path: native/nuget/runtimes/win-x64/native

      - uses: actions/download-artifact@v4
        with:
          name: windows-arm64
          path: native/nuget/runtimes/win-arm64/native

      - uses: actions/download-artifact@v4
        with:
          name: linux-x64
          path: native/nuget/runtimes/linux-x64/native

      - uses: actions/download-artifact@v4
        with:
          name: linux-arm64
          path: native/nuget/runtimes/linux-arm64/native

      - name: Build Package
        run: dotnet pack -c Release -p:Version=${{ github.event.inputs.version }} -o ./packages native/nuget

      - name: Publish Package
        run: dotnet nuget push -s https://nuget.pkg.github.com/aspriddell/index.json -k ${{ github.token }} ./packages/*.nupkg
